### ISSUE TITLE
Cmake variable missing

### ISSUE THREAD

**Issue by deerdear** [CodaProtocol/snark-challenge-prover-reference#7] opened 2019-06-13 09:08 UTC
Trying to `./build.sh` on ubuntu 18.04 on a p2.xlarge instance and I'm getting this error:
```
$ ./build.sh
mkdir: cannot create directory ‘build’: File exists
~/snark-challenge-prover-reference/build ~/snark-challenge-prover-reference
-- The CXX compiler identification is GNU 7.4.0
-- The CUDA compiler identification is NVIDIA 9.1.85
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working CUDA compiler: /usr/bin/nvcc
-- Check for working CUDA compiler: /usr/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Checking for module 'libcrypto'
--   Found libcrypto, version 1.1.1
-- Checking for module 'libprocps'
--   Found libprocps, version 3.3.12
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   program_options
-- The C compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.15")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.1")
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   program_options
-- Found CUDA: /usr (found version "9.1")
-- Automatic GPU detection failed. Building for common architectures.
-- Autodetected CUDA architecture(s): 3.0;3.5;5.0;5.2;6.0;6.1;7.0;7.0+PTX
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
CMake Warning at cuda-fixnum/CMakeLists.txt:39 (message):
  GTest libraries not found - not building test-suite


-- Automatic GPU detection failed. Building for common architectures.
-- Autodetected CUDA architecture(s): 3.0;3.5;5.0;5.2;6.0;6.1;7.0;7.0+PTX
-- Configuring done
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_C_COMPILE_OBJECT
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_C_COMPILE_OBJECT
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_C_COMPILE_OBJECT
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_C_COMPILE_OBJECT
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_C_COMPILE_OBJECT
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_C_COMPILE_OBJECT
[...]
Missing variable is:
CMAKE_C_COMPILE_OBJECT
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_C_CREATE_STATIC_LIBRARY
-- Generating done
-- Build files have been written to: /home/ubuntu/snark-challenge-prover-reference/build
[  9%] Built target zm
[  9%] Building CUDA object cuda-fixnum/CMakeFiles/cuda_main.dir/main.cu.o
[ 58%] Built target ff
[ 96%] Built target snark
ptxas /tmp/tmpxft_0000500f_00000000-11_main.compute_30.ptx, line 328; error   : Instruction 'shf.l' requires .target sm_32 or higher
[...]
ptxas /tmp/tmpxft_0000500f_00000000-11_main.compute_30.ptx, line 17947; error   : Instruction 'shf.l' requires .target sm_32 or higher
ptxas fatal   : Ptx assembly aborted due to errors
cuda-fixnum/CMakeFiles/cuda_main.dir/build.make:62: recipe for target 'cuda-fixnum/CMakeFiles/cuda_main.dir/main.cu.o' failed
make[3]: *** [cuda-fixnum/CMakeFiles/cuda_main.dir/main.cu.o] Error 255
CMakeFiles/Makefile2:706: recipe for target 'cuda-fixnum/CMakeFiles/cuda_main.dir/all' failed
make[2]: *** [cuda-fixnum/CMakeFiles/cuda_main.dir/all] Error 2
CMakeFiles/Makefile2:2419: recipe for target 'libsnark/CMakeFiles/main.dir/rule' failed
make[1]: *** [libsnark/CMakeFiles/main.dir/rule] Error 2
Makefile:955: recipe for target 'main' failed
make: *** [main] Error 2
~/snark-challenge-prover-reference
mv: cannot stat 'build/libsnark/main': No such file or directory
mv: cannot stat 'build/libsnark/generate_parameters': No such file or directory
``` 

I'm not sure if I have to set a CUDA variable or an env. variable. Also, not sure what I have to set them to...

Installing latest `nvcc` version helped some earlier issues I had.

**Comment by o1brad** [comment] 2019-06-13 18:15
Yes, @cmr and I also got this error. Our working theory is that it's caused by libsnark and cuda-fixnum working with different versions of -nvcc. We've got it tested and working with nvcc 10.0.130 but not 10.1.168 (the latest version). If you use this ami (coda-snark-challenge-base-2019-06-11-0816 - ami-08aa2b3568d2de11d), it should have the right version of nvcc installed. We'll look into why the latest version of nvcc isn't automatically detecting the GPU.

**Comment by emberian** [comment] 2019-06-13 18:35
The reason for the build failure here is simple: `-- Automatic GPU detection failed. Building for common architectures.` and the 
"common architectures" include ones too old for cuda-fixnum (which contains some inline PTX assembly). We saw similar GPU detection failures on that instance type sometimes. In those cases `nvidia-smi` would fail. Not sure why.

The missing cmake variable error is relatively benign afaict.

**Comment by emberian** [comment] 2019-06-13 22:05
@deerdear 	can you try running `nvidia-smi` in that instance?

**Comment by deerdear** [comment] 2019-06-14 05:54
So, I switched to the AMI on p2.xlarge after I didn't get it to work on a clean ubuntu install from AWS, and now I'm getting this:
```
~/snark-challenge-prover-reference$ ./generate_parameters fast; time ./main MNT4753 compute CPU MNT4753-parameters MNT4753-input outputs
d = 32767, m = 37155
0
1
2
3
4
5
Segmentation fault (core dumped)

real	0m0.144s
user	0m0.000s
sys	0m0.000s
```
and when I run `nvidia-smi` here, I get:
```
~$ nvidia-smi
Fri Jun 14 06:55:27 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   41C    P0    80W / 149W |      0MiB / 11441MiB |     97%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

When running `nvidia-smi` on a clean ubuntu 16.04 on a p2.xlarge instance, after having run these steps:
`~/ sudo apt-get install build-essential cmake git libgmp3-dev libprocps4-dev python-markdown libboost-all-dev libssl-dev`
`git clone [...]snark-challenge-prover-reference`

Trying `./build.sh` is unsuccessful with the following error: 
```
~/snark-challenge-prover-reference$ ./build.sh
mkdir: cannot create directory 'build': File exists
~/snark-challenge-prover-reference/build ~/snark-challenge-prover-reference
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   program_options
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   program_options
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/snark-challenge-prover-reference/build
[  3%] Building CXX object depends/CMakeFiles/zm.dir/ate-pairing/src/zm2.cpp.o
[  3%] Building CXX object depends/CMakeFiles/zm.dir/ate-pairing/src/zm.cpp.o
/home/ubuntu/snark-challenge-prover-reference/depends/ate-pairing/src/zm2.cpp:1:0: error: bad value (skylake-avx512) for -mtune= switch
 /*
 ^
/home/ubuntu/snark-challenge-prover-reference/depends/ate-pairing/src/zm.cpp:1:0: error: bad value (skylake-avx512) for -mtune= switch
 #include "zm.h"
 ^
compilation terminated due to -Wfatal-errors.
compilation terminated due to -Wfatal-errors.
depends/CMakeFiles/zm.dir/build.make:62: recipe for target 'depends/CMakeFiles/zm.dir/ate-pairing/src/zm.cpp.o' failed
make[3]: *** [depends/CMakeFiles/zm.dir/ate-pairing/src/zm.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
depends/CMakeFiles/zm.dir/build.make:86: recipe for target 'depends/CMakeFiles/zm.dir/ate-pairing/src/zm2.cpp.o' failed
make[3]: *** [depends/CMakeFiles/zm.dir/ate-pairing/src/zm2.cpp.o] Error 1
CMakeFiles/Makefile2:220: recipe for target 'depends/CMakeFiles/zm.dir/all' failed
make[2]: *** [depends/CMakeFiles/zm.dir/all] Error 2
CMakeFiles/Makefile2:2007: recipe for target 'libsnark/CMakeFiles/main.dir/rule' failed
make[1]: *** [libsnark/CMakeFiles/main.dir/rule] Error 2
Makefile:812: recipe for target 'main' failed
make: *** [main] Error 2
~/snark-challenge-prover-reference
mv: cannot stat 'build/libsnark/main': No such file or directory
mv: cannot stat 'build/libsnark/generate_inputs': No such file or directory
mv: cannot stat 'build/libsnark/generate_parameters': No such file or directory
```

Finally when running `nvidia-smi` after having installed nvidia-toolkit I get:
```
nvidia-smi
Fri Jun 14 06:30:45 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.130                Driver Version: 384.130                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   40C    P0    71W / 149W |      0MiB / 11439MiB |     84%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by deerdear** [comment] 2019-06-14 11:40
> Yes, @cmr and I also got this error. Our working theory is that it's caused by libsnark and cuda-fixnum working with different versions of -nvcc. We've got it tested and working with nvcc 10.0.130 but not 10.1.168 (the latest version). If you use this ami (coda-snark-challenge-base-2019-06-11-0816 - ami-08aa2b3568d2de11d), it should have the right version of nvcc installed. We'll look into why the latest version of nvcc isn't automatically detecting the GPU.

I'm using exactly that AMI but I still had to install nvidia-cuda-toolkit, of course it installed the latest version though...

**Comment by emberian** [comment] 2019-06-24 23:51
#11 was merged, which includes a fix for the missing variable. I've opened #12 about the build failing when GPU autodetect fails. Closing this in favor of that.

**Closed as completed by emberian** 2019-06-24 23:51 UTC
